version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: rss-consumer-cron-job
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

networks:
  default:
    external:
      name: rss-consumer-network